# These are supported funding model platforms

github: [xledocteurx]
patreon: lenoirc
open_collective: tyson
ko_fi: # Replace with a single Ko-fi username
tidelift: npm/tyson
custom: # Replace with a single custom sponsorship URL / paypal
