# These are supported funding model platforms

github: [xledocteurx]
patreon: lenoirc
open_collective: soundcase
ko_fi: # Replace with a single Ko-fi username
# tidelift: npm/soundcase
paypal: xledocteurx
custom: # Replace with a single custom sponsorship URL / paypal
