blank_issues_enabled: false
contact_links:
  - name: Create new issue
    url: https://new-issue.tyson.org/ #lien github issues
    about: Please use the following link to create a new issue.
  - name: Patreon
    url: https://www.patreon.com/evanyou
    about: Love Tyson? Please consider supporting us via Patreon.
  - name: Open Collective
    url: https://opencollective.com/tyson/donate
    about: Love Tyson? Please consider supporting us via Open Collective.
